"""PCA utilities for the Paddy Dataset project."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA


def project_root_from_file() -> Path:
    """Return the project root assuming this file lives in src/."""

    return Path(__file__).resolve().parents[1]


def load_processed_features(path: str | Path) -> pd.DataFrame:
    """Load the preprocessed feature matrix generated by preprocessing.py."""

    return pd.read_csv(path)


def fit_pca(features: pd.DataFrame, variance_threshold: float = 0.95) -> tuple[PCA, pd.DataFrame, dict]:
    """Fit PCA and return coordinates, explained variance table, and metadata."""

    pca = PCA()
    coordinates = pca.fit_transform(features)

    explained_variance = pd.DataFrame(
        {
            "component": [f"PC{i + 1}" for i in range(len(pca.explained_variance_ratio_))],
            "explained_variance_ratio": pca.explained_variance_ratio_,
            "cumulative_explained_variance": pca.explained_variance_ratio_.cumsum(),
            "eigenvalue": pca.explained_variance_,
        }
    )

    components_needed = int(
        (explained_variance["cumulative_explained_variance"] < variance_threshold).sum() + 1
    )
    coordinate_columns = [f"PC{i + 1}" for i in range(coordinates.shape[1])]
    coordinate_df = pd.DataFrame(coordinates, columns=coordinate_columns, index=features.index)

    metadata = {
        "input_rows": int(features.shape[0]),
        "input_features": int(features.shape[1]),
        "variance_threshold": variance_threshold,
        "components_for_threshold": components_needed,
        "pc1_explained_variance": float(pca.explained_variance_ratio_[0]),
        "pc2_explained_variance": float(pca.explained_variance_ratio_[1]),
        "pc1_pc2_cumulative_variance": float(
            pca.explained_variance_ratio_[:2].sum()
        ),
    }
    return pca, coordinate_df, explained_variance, metadata


def save_pca_outputs(
    coordinates: pd.DataFrame,
    explained_variance: pd.DataFrame,
    metadata: dict,
    output_dir: str | Path,
    table_dir: str | Path,
    figure_dir: str | Path,
) -> None:
    """Save PCA tables, coordinate CSVs, and diagnostic figures."""

    output_path = Path(output_dir)
    table_path = Path(table_dir)
    figure_path = Path(figure_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    table_path.mkdir(parents=True, exist_ok=True)
    figure_path.mkdir(parents=True, exist_ok=True)

    coordinates.to_csv(output_path / "pca_coordinates_all_components.csv", index=False)
    coordinates[["PC1", "PC2"]].to_csv(output_path / "pca_coordinates_2d.csv", index=False)
    explained_variance.to_csv(table_path / "pca_explained_variance.csv", index=False)
    (table_path / "pca_metadata.json").write_text(
        json.dumps(metadata, indent=2),
        encoding="utf-8",
    )

    fig, ax = plt.subplots(figsize=(9, 5))
    first_components = explained_variance.head(20)
    ax.bar(
        first_components["component"],
        first_components["explained_variance_ratio"],
        color="#2E86AB",
    )
    ax.set_title("PCA Explained Variance by Component")
    ax.set_xlabel("Principal Component")
    ax.set_ylabel("Explained Variance Ratio")
    ax.tick_params(axis="x", rotation=45)
    fig.tight_layout()
    fig.savefig(figure_path / "pca_explained_variance_first_20.png", bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(
        explained_variance["component"],
        explained_variance["cumulative_explained_variance"],
        marker="o",
        markersize=3,
        linewidth=1.5,
        color="#5B8E7D",
    )
    ax.axhline(
        metadata["variance_threshold"],
        color="#C8553D",
        linestyle="--",
        linewidth=1,
        label=f"{metadata['variance_threshold']:.0%} threshold",
    )
    ax.axvline(
        metadata["components_for_threshold"] - 1,
        color="#C8553D",
        linestyle=":",
        linewidth=1,
    )
    ax.set_title("PCA Cumulative Explained Variance")
    ax.set_xlabel("Principal Component")
    ax.set_ylabel("Cumulative Explained Variance")
    ax.set_ylim(0, 1.02)
    ax.set_xticks(range(0, len(explained_variance), 5))
    ax.set_xticklabels(explained_variance["component"].iloc[::5], rotation=45)
    ax.legend()
    fig.tight_layout()
    fig.savefig(figure_path / "pca_cumulative_explained_variance.png", bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.scatter(coordinates["PC1"], coordinates["PC2"], s=14, alpha=0.65, color="#2E86AB")
    ax.set_title("Paddy Farms Projected onto First Two Principal Components")
    ax.set_xlabel(f"PC1 ({metadata['pc1_explained_variance']:.1%})")
    ax.set_ylabel(f"PC2 ({metadata['pc2_explained_variance']:.1%})")
    fig.tight_layout()
    fig.savefig(figure_path / "pca_2d_projection.png", bbox_inches="tight")
    plt.close(fig)


def run_pca(
    features_path: str | Path,
    output_dir: str | Path,
    table_dir: str | Path,
    figure_dir: str | Path,
    variance_threshold: float = 0.95,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Load processed features, fit PCA, and save outputs."""

    features = load_processed_features(features_path)
    _, coordinates, explained_variance, metadata = fit_pca(
        features,
        variance_threshold=variance_threshold,
    )
    save_pca_outputs(
        coordinates=coordinates,
        explained_variance=explained_variance,
        metadata=metadata,
        output_dir=output_dir,
        table_dir=table_dir,
        figure_dir=figure_dir,
    )
    return coordinates, explained_variance, metadata


def parse_args() -> argparse.Namespace:
    root = project_root_from_file()
    parser = argparse.ArgumentParser(description="Run PCA on processed Paddy features.")
    parser.add_argument(
        "--features-path",
        type=Path,
        default=root / "outputs" / "processed" / "processed_features.csv",
        help="Path to processed_features.csv.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=root / "outputs" / "processed",
        help="Directory for PCA coordinate outputs.",
    )
    parser.add_argument(
        "--table-dir",
        type=Path,
        default=root / "outputs" / "tables",
        help="Directory for PCA summary tables.",
    )
    parser.add_argument(
        "--figure-dir",
        type=Path,
        default=root / "outputs" / "figures",
        help="Directory for PCA figures.",
    )
    parser.add_argument(
        "--variance-threshold",
        type=float,
        default=0.95,
        help="Cumulative explained variance threshold.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    _, explained_variance, metadata = run_pca(
        features_path=args.features_path,
        output_dir=args.output_dir,
        table_dir=args.table_dir,
        figure_dir=args.figure_dir,
        variance_threshold=args.variance_threshold,
    )
    print(f"Input features: {metadata['input_features']:,}")
    print(f"PC1 variance: {metadata['pc1_explained_variance']:.4f}")
    print(f"PC2 variance: {metadata['pc2_explained_variance']:.4f}")
    print(f"PC1 + PC2 variance: {metadata['pc1_pc2_cumulative_variance']:.4f}")
    print(
        f"Components for {metadata['variance_threshold']:.0%} variance: "
        f"{metadata['components_for_threshold']}"
    )
    print("Top 10 components:")
    print(explained_variance.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
